name: Main-worker

# on:
#   push:
#     branches: [ "devops" ]
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to use for this workflow' # Provide a description
        required: true # Set to true to make this input mandatory
        default: 'devops' 

env:
  PROJECT_ID: ocean-246520
  GAR_NAME: ocean
  GAR_LOCATION: us-east4
  SERVICE: main-worker
  REGION: us-east4
     
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: test
        run: |
          ls

            
      